# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				pufferfish = true
				item = true
				axolotl = true
				villager = true
				cow = true
				ocelot = true
				tropical_fish = true
				boat = true
				hopper_minecart = true
				skeleton = true
				bat = true
				zombie = true
				armor_stand = true
				cod = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				parrot = true
				spider = true
				sheep = true
				creeper = true
				player = true

